### ISSUE TITLE
plugin doesn't seem to parse kubeconfig with oidc configured. 

### ISSUE THREAD

**Issue by mauilion** [stefanprodan/kubectl-kubesec#3]
example kubeconfig leveraging oidc against dex:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/dcooley/ca-px-prd1002.pem
    server: https://k8s-api.v.k8s.work:6443
  name: px-prd1002
contexts:
- context:
    cluster: px-prd1002
    namespace: identity
    user: qa@k8s.work
  name: px-prd1002
current-context: px-prd1002
kind: Config
preferences: {}
users:
- name: qa@k8s.work
  user:
    auth-provider:
      config:
        client-id: gangway
        client-secret: supersecret
        id-token: <redacted>
        idp-issuer-url: https://identity.v.k8s.work/identity
        refresh-token: <redacted>
      name: oidc
```
gets me:

```
$ kubectl -n identity plugin scan deployment/dex
panic: No Auth Provider found for name "oidc"

goroutine 1 [running]:
github.com/stefanprodan/kubectl-kubesec/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1.NewForConfigOrDie(0xc420171340, 0xc4202e0690)
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1/admissionregistration_client.go:60 +0x65
github.com/stefanprodan/kubectl-kubesec/vendor/k8s.io/client-go/kubernetes.NewForConfigOrDie(0xc420171340, 0x10c42e0)
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/vendor/k8s.io/client-go/kubernetes/clientset.go:529 +0x49
main.loadConfig(0x7ffd6b549f3c, 0xe, 0xfdce16)
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/main.go:136 +0x4e
main.main()
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/main.go:45 +0xbf
error: exit status 2
```
If I create an serviceaccount and generate a kubeconfig using it's token things work fine.

**Comment by stefanprodan** [comment]
Hi @mauilion 

What Kubernetes version are you using?

**Comment by mauilion** [comment]
v1.10.3 in this case
